apiVersion: v1
kind: Service
metadata:
  name: glados-service-backend
  namespace: default
  labels:
    app: GLADOS
spec:
  selector:
    app: GLADOS
    tier: backend
  ports:
    - protocol: TCP
      port: 0000
      targetPort: 0000