apiVersion: batch/v1
kind: Job
metadata:
  name: runner
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: GLADOS
    spec:
      containers:
      - name: runner
        image: gladospipeline/glados-runner:main
        imagePullPolicy: Always
        command: []
      restartPolicy: Never
  backoffLimit: 4
  ttlSecondsAfterFinished: 60
