# Usage
#   Start:          docker-compose up
#   With helpers:   docker-compose -f docker-compose.yml -f ./dev/docker-compose.dev.yml up
#   Stop:           docker-compose down
#   Destroy:        docker-compose -f docker-compose.yml -f ./dev/docker-compose.dev.yml down -v --remove-orphans

version: '3.8'
name: glados-project

services:
  app-backend:
    build:
      context: ./apps/backend
      dockerfile: ./backend.Dockerfile
    container_name: glados-backend
    environment:
      creds: ${FIREBASE_KEY}
    volumes:
        - ./apps/backend/ExperimentFiles:/app/ExperimentFiles
    # restart: always # TODO does having this commented out prevent it from turning back on any time the docker engine restarts?
    # TODO switch to ${BACKEND_PORT}
    ports:
        # TODO does this need to be exposed to host?
        - 5050:5050
    expose:
        - "5050"

  app-frontend:
    build:
      context: ./apps/frontend
      dockerfile: ./frontend.Dockerfile
    container_name: glados-frontend
    volumes:
      - ./apps/frontend:/home/node/app
    working_dir: /home/node/app
    # TODO switch to ${FRONTEND_WEBSERVER_PORT}
    ports:
      - 3000:3000
    expose:
      - "3000"
