# Usage
#   Start:          docker-compose up
#   With helpers:   docker-compose -f docker-compose.yml -f ./dev/docker-compose.dev.yml up
#   Stop:           docker-compose down
#   Destroy:        docker-compose -f docker-compose.yml -f ./dev/docker-compose.dev.yml down -v --remove-orphans

version: '3.8'
name: glados-project

services:
  app-backend:
      build:
        context: ./apps/backend
        # dockerfile: ./Dockerfile # TODO there wasn't one in the old location?
      # image: glados-backend # TODO was still commented out in old
      container_name: glados-backend
      environment:
        creds: ${FIREBASE_KEY}
      volumes:
          - ./apps/backend/ExperimentFiles:/app/ExperimentFiles
      restart: always
      ports:
          - 5050:5050
      expose:
          - "5050"
