apiVersion: batch/v1
kind: Job
metadata:
  name: runner
spec:
  template:
    metadata:
      labels:
        app: GLADOS
    spec:
      containers:
      - name: runner
        image: gladospipeline/glados-runner:latest
        imagePullPolicy: Always
        command: []
        env:
        - name: MONGODB_PORT
          valueFrom:
            secretKeyRef:
              name: secret-env
              key: MONGODB_PORT
        - name: SERVICE_ROLE_KEY
          valueFrom:
            secretKeyRef:
              name: secret-env
              key: SERVICE_ROLE_KEY
        - name: FIREBASE_KEY
          valueFrom:
            secretKeyRef:
              name: secret-env
              key: FIREBASE_KEY
        - name: MONGODB_USERNAME
          valueFrom:
            secretKeyRef:
              name: secret-env
              key: MONGODB_USERNAME
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-env
              key: MONGODB_PASSWORD
        - name: BACKEND_PORT
          valueFrom:
            secretKeyRef:
              name: secret-env
              key: BACKEND_PORT
      restartPolicy: Never
  backoffLimit: 4
  ttlSecondsAfterFinished: 60