apiVersion: batch/v1
kind: Job
metadata:
  name: runner
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: GLADOS
    spec:
      containers:
      - name: runner
        image: gladospipeline/glados-runner:main
        imagePullPolicy: Always
        command: []
        resources:
          requests:
            cpu: "250m"      # 0.25 cores
            memory: "256Mi"
          limits:
            cpu: "500m"      # 0.5 cores max
            memory: "512Mi"
        env:
        - name: MONGODB_PORT
          valueFrom:
            secretKeyRef:
              name: secret-env
              key: MONGODB_PORT
        - name: BACKEND_PORT
          valueFrom:
            secretKeyRef:
              name: secret-env
              key: BACKEND_PORT
        - name: GMAIL_CREDS
          valueFrom:
            secretKeyRef:
              name: secret-env
              key: GMAIL_CREDS
      restartPolicy: Never
  backoffLimit: 2
  ttlSecondsAfterFinished: 60
