
apiVersion: v1
kind: Service
metadata:
  name: app-backend-service
spec:
  selector:
    app: app-backend
  ports:
  - protocol: "TCP"
    port: 5050
    targetPort: 5050
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-backend
spec:
  selector:
    matchLabels:
      app: app-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: app-backend
    spec:
      containers:
      - name: glados-backend
        image: glados-backend
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5050
