# kinda building off of this https://kubernetes.io/docs/concepts/storage/volumes/#local
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-0
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  hostPath:
    path: "/srv/data/mongo-1" # change to where it is locally (For minikube, may need to mount: https://stackoverflow.com/questions/63559779/kubernetes-minikube-persistent-volume-local-filesystem-storage-location)
---
# kinda building off of this https://kubernetes.io/docs/concepts/storage/volumes/#local
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-1
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  hostPath:
    path: "/srv/data/mongo-2" # change to where it is locally (For minikube, may need to mount: https://stackoverflow.com/questions/63559779/kubernetes-minikube-persistent-volume-local-filesystem-storage-location)
