apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: glados-mongodb
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glados-mongodb
  strategy: {}
  template:
    metadata:
      labels:
        app: glados-mongodb
    spec:
      containers:
      - image: mongo
        name: mongo
        args: ["--dbpath","/data/db"]
        livenessProbe:
          exec:
            command:
              - mongosh
              - --norc
              - --quiet
              - --eval
              - "db.getMongo()"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
              - mongosh
              - --norc
              - --quiet
              - --eval
              - "db.getMongo()"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: secret-env
              key: MONGODB_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-env
              key: MONGODB_PASSWORD
        volumeMounts:
        - name: "mongo-data-dir"
          mountPath: "srv/data/db"
      volumes:
      - name: "mongo-data-dir"
        persistentVolumeClaim:
          claimName: "pvc"
      nodeName: glados-db