apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: glados-mongo
  namespace: mongodb
spec:
  serviceName: "glados-service-mongodb"
  replicas: 3
  selector:
    matchLabels:
      app: glados-mongodb
  template:
    metadata:
      labels:
        app: glados-mongodb
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /srv/data/db
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: secret-env
              key: MONGODB_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-env
              key: MONGODB_PASSWORD
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      accessModes: 
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
