apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: glados-mongo
spec:
  serviceName: "glados-service-mongodb"
  replicas: 3
  selector:
    matchLabels:
      app: glados-mongodb
  template:
    metadata:
      labels:
        app: glados-mongodb
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        command: ["mongod", "--replSet", "rs0", "--bind_ip", "0.0.0.0"]  # Enable replication
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: local-storage
          mountPath: /srv/data/db  # MongoDB default data directory is /data/db
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: secret-env
              key: MONGODB_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-env
              key: MONGODB_PASSWORD
  volumeClaimTemplates:
  - metadata:
      name: local-storage
    spec:
      accessModes: 
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
