# values.yaml
architecture: replicaset

image: 
  registry: docker.io 
  repository: bitnamilegacy/mongodb 
  tag: 8.0.13

replicaSet:
  enabled: true
  replicas: 3 # Set the number of replicas
  waitForPrimary: true

persistence:
  enabled: true
  storageClass: local-storage # Use the storage class created earlier
  accessModes:
    - ReadWriteOnce
  size: 10Gi # Adjust the size as needed

auth:
  enabled: true
  rootUser: "adminuser"
  rootPassword: "password123"

service:
  nameOverride: glados-service-mongodb

externalAccess:
  enabled: true
  service:
    type: NodePort
    nodePorts: [30000, 30001]
