
export const addNumsExpData = {
    "hyperparameters": "{\"hyperparameters\":[{\"name\":\"x\",\"default\":\"1\",\"min\":\"1\",\"max\":\"10\",\"step\":\"1\",\"type\":\"integer\"},{\"name\":\"y\",\"default\":\"1\",\"min\":\"1\",\"max\":\"10\",\"step\":\"1\",\"type\":\"integer\"}]}",
    "finished": true,
    "expId": "addNumsDefaultExperiment",
    "startedAtEpochMillis": 1727571672152,
    "estimatedTotalTimeMinutes": 0.054472017288208004,
    "timeout": 18000,
    "scatterDepVar": "",
    "scatterIndVar": "",
    "workers": 1,
    "trialExtraFile": "AddNumResult.csv",
    "keepLogs": true,
    "creator": "DefaultRunner",
    "verbose": false,
    "file": "https://raw.githubusercontent.com/AutomatingSciencePipeline/Monorepo/refs/heads/main/example_experiments/python/addNums.py",
    "trialResult": "AddNumResult.csv",
    "dumbTextArea": "",
    "totalExperimentRuns": 18,
    "description": "",
    "name": "Add Nums Default Experiment Python",
    "passes": 18,
    "finishedAtEpochMillis": 1727571675975,
    "created": 1727571652754,
    "scatter": false
}

export const multistringPy = {
    "hyperparameters": "{\"hyperparameters\":[{\"name\":\"x\",\"default\":\"1\",\"min\":\"1\",\"max\":\"10\",\"step\":\"1\",\"type\":\"integer\"},{\"name\":\"values\",\"default\":\"11\",\"values\":[\"a\",\"b\"],\"type\":\"stringlist\"}]}",
    "finished": true,
    "expId": "MultiStringDefaultExperiment",
    "startedAtEpochMillis": 1727571672152,
    "estimatedTotalTimeMinutes": 0.054472017288208004,
    "timeout": 18000,
    "scatterDepVar": "",
    "scatterIndVar": "",
    "workers": 1,
    "trialExtraFile": "stringResult.csv",
    "keepLogs": true,
    "creator": "DefaultRunner",
    "verbose": false,
    "file": "https://raw.githubusercontent.com/AutomatingSciencePipeline/Monorepo/refs/heads/main/example_experiments/python/multiString.py",
    "trialResult": "stringResult.csv",
    "dumbTextArea": "",
    "totalExperimentRuns": 18,
    "description": "",
    "name": "Multi String Default Experiment Python",
    "passes": 18,
    "finishedAtEpochMillis": 1727571675975,
    "created": 1727571652754,
    "scatter": false
}

export const geneticalgo = {
    "hyperparameters": "{\"hyperparameters\":[{\"name\":\"p\",\"default\":\"1\",\"min\":\"1\",\"max\":\"10\",\"step\":\"1\",\"type\":\"integer\"},{\"name\":\"g\",\"default\":\"60\",\"min\":\"60\",\"max\":\"100\",\"step\":\"20\",\"type\":\"integer\"}, {\"name\":\"gl\",\"default\":\"1\",\"min\":\"1\",\"max\":\"20\",\"step\":\"1\",\"type\":\"integer\"}, {\"name\":\"mr\",\"default\":\"0.2\",\"min\":\"0.1\",\"max\":\"0.8\",\"step\":\"0.1\",\"type\":\"float\"}]}",
    "finished": true,
    "expId": "GeneticAlgoDefaultExperiment",
    "startedAtEpochMillis": 1727571672152,
    "estimatedTotalTimeMinutes": 0.054472017288208004,
    "timeout": 18000,
    "scatterDepVar": "",
    "scatterIndVar": "",
    "workers": 1,
    "trialExtraFile": "geneticRes.csv",
    "keepLogs": true,
    "creator": "DefaultRunner",
    "verbose": false,
    "file": "https://raw.githubusercontent.com/AutomatingSciencePipeline/Monorepo/refs/heads/main/example_experiments/python/genetic_algorithm.py",
    "trialResult": "geneticRes.csv",
    "dumbTextArea": "seed=1",
    "totalExperimentRuns": 18,
    "description": "",
    "name": "Genetric Algorithm Default Experiment",
    "passes": 18,
    "finishedAtEpochMillis": 1727571675975,
    "created": 1727571652754,
    "scatter": false
}