# Configuration, see https://www.mkdocs.org/user-guide/configuration/
site_name: GLADOS
site_description: Documentation for GLADOS - Automated Science Pipeline
site_url: https://automatingsciencepipeline.github.io/Monorepo/

repo_url: https://github.com/AutomatingSciencePipeline/Monorepo
edit_uri: '' # edit is hidden

# Site navigation - remember to update when creating new pages!
nav:
  - Home: index.md
  - About GLADOS: about.md
  - BioAI User Guides:
    - HW8: bioai/hw8.md
  - Tutorial:
    - Usage: tutorial/usage.md
    - Installation: tutorial/installation.md
    - Local GLADOS Installation (Updated Nov 2024): tutorial/local_testing.md
    - Developer Installation: tutorial/developer_installation.md
    - Deployment: tutorial/deployment.md
    - Developer Deployment: tutorial/developer_deployment.md
    - Troubleshooting: tutorial/troubleshooting.md
  - Documentation:
    - Updating Documentation: documentation/guide.md
  - Infrastructure:
    - Kubernetes: infrastructure/kubernetes.md
    - VMs: infrastructure/vms.md
    - Cluster Upgrade: infrastructure/cluster_update.md
    - Used Technologies: infrastructure/used_technologies.md
  - Developer Help:
    - Helpful Commands: developerhelp/helpful_commands.md
  - Cheatsheet: cheatsheet.md
  - (Old) Repository Guide: repository_guide.md

# Drafts are excluded from deployments, but are shown while using `mkdocs serve`.
draft_docs: |
  drafts/

# Read about themes here: https://www.mkdocs.org/user-guide/choosing-your-theme/
theme: 
  name: material
  features:
    - content.code.copy
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Markdown Extensions supported by mkdocs-material here: https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/
markdown_extensions:
  # https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#definition-lists
  - def_list
  # # https://yakworks.github.io/docmark/extensions/permalinks/
  # - toc(permalink=true)
  - tables
