apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: metallb-system
spec:
  addresses:
  # dev is 137.112.104.86
  - 137.112.104.84/32 # This is the ip address for the hostname glados.csse.rose-hulman.edu