apiVersion: apps/v1
kind: Deployment
metadata:
  name: glados-frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: GLADOS
      tier: frontend
  template:
    metadata:
      labels:
        app: GLADOS
        tier: frontend
    spec:
      containers:
        - name: glados-frontend
          image: bveal/glados-frontend:main
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              hostPort: 3000 
          env:
            - name: BACKEND_PORT
              valueFrom:
                secretKeyRef:
                  name: secret-env
                  key: BACKEND_PORT
            - name: FRONTEND_WEBSERVER_PORT
              valueFrom:
                secretKeyRef:
                  name: secret-env
                  key: FRONTEND_WEBSERVER_PORT
            - name: MONGODB_PORT
              valueFrom:
                secretKeyRef:
                  name: secret-env
                  key: MONGODB_PORT
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret-env
                  key: MONGODB_USERNAME
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-env
                  key: MONGODB_PASSWORD
            - name: AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: secret-env
                  key: AUTH_SECRET
            - name: AUTH_GITHUB_ID
              valueFrom:
                secretKeyRef:
                  name: secret-env
                  key: AUTH_GITHUB_ID
            - name: AUTH_GITHUB_SECRET
              valueFrom:
                secretKeyRef:
                  name: secret-env
                  key: AUTH_GITHUB_SECRET
            - name: AUTH_GOOGLE_ID
              valueFrom:
                secretKeyRef:
                  name: secret-env
                  key: AUTH_GOOGLE_ID
            - name: AUTH_GOOGLE_SECRET
              valueFrom:
                secretKeyRef:
                  name: secret-env
                  key: AUTH_GOOGLE_SECRET
            - name: AUTH_TRUST_HOST
              valueFrom:
                secretKeyRef:
                  name: secret-env
                  key: AUTH_TRUST_HOST
            - name: AUTH_URL
              valueFrom:
                secretKeyRef:
                  name: secret-env
                  key: AUTH_URL
            - name: AUTH_REDIRECT_PROXY_URL
              valueFrom:
                secretKeyRef:
                  name: secret-env
                  key: AUTH_REDIRECT_PROXY_URL
