apiVersion: v1
kind: Service
metadata:
  name: glados-service-frontend
spec:
  selector:
    app: GLADOS # Ensure this matches the pod label
  ports:
    - protocol: TCP
      port: 3000 # The service port
      targetPort: 3000 # The container port where Next.js listens
  type: LoadBalancer # Expose service with a load balancer
