apiVersion: v1
kind: Service
metadata:
  name: glados-service-frontend
spec:
  selector:
    app: GLADOS  # This should match the pod labels
  ports:
    - protocol: TCP
      port: 3000       # The service port (accessible inside the cluster)
      targetPort: 3000  # The container's port
      nodePort: 30000   # The external port
  type: NodePort