apiVersion: v1
kind: Service
metadata:
  name: glados-service-frontend
  namespace: default
  labels:
    app: GLADOS
spec:
  selector:
    app: GLADOS
    tier: frontend
  type: LoadBalancer
  ports:
  - name: https
    port: 80
    targetPort: 3000
  - name: http
    port: 3000
    targetPort: 3000