apiVersion: v1
kind: Service
metadata:
  name: glados-service-frontend
  namespace: default
  labels:
    app: GLADOS
spec:
  selector:
    app: GLADOS
    tier: frontend
  # type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000