apiVersion: v1
kind: Service
metadata:
  name: glados-frontend-service
spec:
  selector:
    app: GLADOS
    tier: frontend
  ports:
    - protocol: TCP
      port: 3000     # The port exposed by the Service
      targetPort: 3000 # The port your Next.js app listens on
  type: ClusterIP