
export const addNumsExpData = {
    "hyperparameters": "{\"hyperparameters\":[{\"name\":\"x\",\"default\":\"1\",\"min\":\"1\",\"max\":\"10\",\"step\":\"1\",\"type\":\"integer\"},{\"name\":\"y\",\"default\":\"1\",\"min\":\"1\",\"max\":\"10\",\"step\":\"1\",\"type\":\"integer\"}]}",
    "finished": true,
    "expId": "addNumsDefaultExperiment",
    "startedAtEpochMillis": 1727571672152,
    "estimatedTotalTimeMinutes": 0.054472017288208004,
    "timeout": 18000,
    "scatterDepVar": "",
    "scatterIndVar": "",
    "workers": 1,
    "trialExtraFile": "AddNumResult.csv",
    "keepLogs": true,
    "creator": "DefaultRunner",
    "verbose": false,
    "file": "https://raw.githubusercontent.com/AutomatingSciencePipeline/Monorepo/refs/heads/main/example_experiments/python/addNums.py",
    "trialResult": "AddNumResult.csv",
    "dumbTextArea": "",
    "totalExperimentRuns": 18,
    "description": "",
    "name": "Add Nums Default Experiment Python",
    "passes": 18,
    "finishedAtEpochMillis": 1727571675975,
    "created": 1727571652754,
    "scatter": false
}