name: Node.js CI

on:
  push:
    branches: [ GitHub-CI-Research ] #change to main when using it for real
  pull_request:
    branches: [ GitHub-CI-Research ] 

jobs:
  Lint_And_Test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # List the node versions we want to support here, and it will test all of them
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        working-directory: ./apps/frontend
        run: npm ci
      - name: Run ESLint
        working-directory: ./apps/frontend
        # https://eslint.org/docs/latest/use/command-line-interface#run-the-cli
        # Run on any ts, tsx, js, jsx files recursively in the working directory
        # Uses the .eslintrc.json rules file in the working directory
        # run: npx eslint --ignore-pattern "./node_modules/*" **/*.ts **/*.tsx **/*.js **/*.jsx
        run: npm run lint
      - name: Run NPM Test
        working-directory: ./apps/frontend
        run: npm test
