name: Node.js Lint and Test

on:
  push:
    paths:
      - 'apps/frontend/**'
    branches: [ main ] 
  pull_request:
    paths:
      - 'apps/frontend/**'
    branches: [ main ] 

jobs:
  Lint_And_Test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # List the node versions we want to support here, and it will test all of them
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        working-directory: ./apps/frontend
        run: npm ci
      - name: Run ESLint
        working-directory: ./apps/frontend
        run: npm run lint
      - name: Run Typescript Check
        working-directory: ./apps/frontend
        run: npm run type-check
      - name: Run NPM Test
        working-directory: ./apps/frontend
        # TODO is this the right command to run? we'll know once we have tests
        run: npm test
