# This workflow tests if the Supabase container is valid.
# We aren't using Supabase any more, so we don't need it,
# but holding onto it as it will help us verify our other containers later. - Rob

# name: Docker-Compose-Actions-Workflow
# on: 
#   schedule:
#   - cron: '18 6 * * *'
# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Build the stack
#         working-directory: ./services/supabase
#         run: docker-compose up -d --build
