name: Python CI

on:
  push:
    branches: [ GitHub-CI-Research ]
  pull_request:
    branches: [ GitHub-CI-Research ]

permissions:
  contents: read
env:
  FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      working-directory: ./apps/backend
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev --system --deploy --ignore-pipfile
    - name: Analysing the code with pylint
      # https://stackoverflow.com/questions/73232772/pylint-fail-under-does-not-fail-my-github-action-job
      run: |
        pylint --fail-under=10.0 --recursive=y app.py ./modules/ ./tests/
    - name: Test with pytest
      working-directory: ./apps/backend
      run: pytest
