name: Python Lint and Test

on:
  push:
    branches: [ Adding-Testing-Coverage ]
  pull_request:
    branches: [ Adding-Testing-Coverage ]

permissions:
  contents: read
env:
  FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
jobs:
  Lint_And_Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      working-directory: ./apps/backend
      run: |
        python -m pip install --upgrade pip
        python -m pip install coverage
        pip install pipenv
        pipenv install --dev --system --deploy --ignore-pipfile
    - name: Analyze with pylint
      working-directory: ./apps/backend
      # https://pylint.readthedocs.io/en/v2.16.1/user_guide/configuration/all-options.html#fail-on
      # Uses the .pylintrc rules file in the working directory
      # Fail if any Error-level notices were produced
      # Fail if the code quality score is below 9.0
      # Recursively search the specified directories for files to analyze
      # Check the file app.py
      # Check the directories ./modules and ./tests
      run: pylint --fail-on=E --fail-under=9.0 --recursive=y app.py ./modules/ ./tests/
    - name: Test with pytest
      working-directory: ./apps/backend
      run: coverage run -m pytest
    - name: Printing Coverage Report
      working-directory: ./apps/backend
      run: coverage report -m
