# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  # Run this action at 6:18am daily
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
  - cron: '18 6 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
        days-before-stale: 30
        stale-issue-message: 'This issue has been inactive for 30 days'
        stale-pr-message: 'This PR has been inactive for 30 days'
        days-before-close: -1 # Never actually close items
